export const playersData = [
  {
    name: 'Cristiano Ronaldo',
    id: 1,
    market_price: 232,
    specialization: 'futsal',
    player_record: 'Olympic Special',
    quantity: 1,
    desc: 'Neque aut veniam consectetur magnam libero, natus eius numquam reprehenderit hic at, excepturi repudiandae magni optio odio doloribus? Facilisi lobortisal morbi fringilla urna amet sed ipsum.',
  },
  {
    name: 'Lionel Messi',
    id: 2,
    market_price: 900,
    specialization: 'basketball',
    player_record: 'Record Special',
    quantity: 1,
    desc: 'Neque aut veniam consectetur magnam libero, natus eius numquam reprehenderit hic at, excepturi repudiandae magni optio odio doloribus? Facilisi lobortisal morbi fringilla urna amet sed ipsum.',
  },
  {
    name: 'Neymar Jr',
    id: 3,
    market_price: 800,
    specialization: 'futsal',
    player_record: 'Hall of Fame',
    quantity: 1,
    desc: 'Neque aut veniam consectetur magnam libero, natus eius numquam reprehenderit hic at, excepturi repudiandae magni optio odio doloribus? Facilisi lobortisal morbi fringilla urna amet sed ipsum.',
  },
  {
    name: 'Kylian Mbappe',
    id: 4,
    market_price: 1200,
    specialization: 'swimming',
    player_record: 'Olympic Special',
    quantity: 1,
    desc: 'Neque aut veniam consectetur magnam libero, natus eius numquam reprehenderit hic at, excepturi repudiandae magni optio odio doloribus? Facilisi lobortisal morbi fringilla urna amet sed ipsum.',
  },
  {
    name: 'Mohamed Salah',
    id: 5,
    market_price: 700,
    specialization: 'futsal',
    player_record: 'Record Special',
    quantity: 1,
    desc: 'Neque aut veniam consectetur magnam libero, natus eius numquam reprehenderit hic at, excepturi repudiandae magni optio odio doloribus? Facilisi lobortisal morbi fringilla urna amet sed ipsum.',
  },
  {
    name: 'Kevin De Bruyne',
    id: 6,
    market_price: 800,
    specialization: 'basketball',
    quantity: 1,
    desc: 'Neque aut veniam consectetur magnam libero, natus eius numquam reprehenderit hic at, excepturi repudiandae magni optio odio doloribus? Facilisi lobortisal morbi fringilla urna amet sed ipsum.',

    player_record: 'Hall of Fame',
  },
  {
    name: 'Virgil van Dijk',
    id: 7,
    market_price: 600,
    specialization: 'swimming',
    player_record: 'Record Special',
    quantity: 1,
    desc: 'Neque aut veniam consectetur magnam libero, natus eius numquam reprehenderit hic at, excepturi repudiandae magni optio odio doloribus? Facilisi lobortisal morbi fringilla urna amet sed ipsum.',
  },
  {
    name: 'Robert Lewandowski',
    id: 8,
    market_price: 950,
    specialization: 'futsal',
    player_record: 'Hall of Fame',
    quantity: 1,
    desc: 'Neque aut veniam consectetur magnam libero, natus eius numquam reprehenderit hic at, excepturi repudiandae magni optio odio doloribus? Facilisi lobortisal morbi fringilla urna amet sed ipsum.',
  },
  {
    name: 'Kylian Mbappe',
    id: 421,
    market_price: 1200,
    specialization: 'swimming',
    player_record: 'Olympic Special',
    quantity: 1,
    desc: 'Neque aut veniam consectetur magnam libero, natus eius numquam reprehenderit hic at, excepturi repudiandae magni optio odio doloribus? Facilisi lobortisal morbi fringilla urna amet sed ipsum.',
  },
  {
    name: 'Mohamed Salah',
    id: 5323,
    market_price: 700,
    specialization: 'futsal',
    player_record: 'Record Special',
    quantity: 1,
    desc: 'Neque aut veniam consectetur magnam libero, natus eius numquam reprehenderit hic at, excepturi repudiandae magni optio odio doloribus? Facilisi lobortisal morbi fringilla urna amet sed ipsum.',
  },
  {
    name: 'Kevin De Bruyne',
    id: 2126,
    market_price: 800,
    specialization: 'basketball',
    quantity: 1,
    desc: 'Neque aut veniam consectetur magnam libero, natus eius numquam reprehenderit hic at, excepturi repudiandae magni optio odio doloribus? Facilisi lobortisal morbi fringilla urna amet sed ipsum.',
    player_record: 'Hall of Fame',
  },
  {
    name: 'Virgil van Dijk',
    id: 217,
    market_price: 600,
    specialization: 'swimming',
    player_record: 'Record Special',
    quantity: 1,
    desc: 'Neque aut veniam consectetur magnam libero, natus eius numquam reprehenderit hic at, excepturi repudiandae magni optio odio doloribus? Facilisi lobortisal morbi fringilla urna amet sed ipsum.',
  },
  {
    name: 'Robert Lewandowski',
    id: 111,
    market_price: 950,
    specialization: 'futsal',
    player_record: 'Hall of Fame',
    quantity: 1,
    desc: 'Neque aut veniam consectetur magnam libero, natus eius numquam reprehenderit hic at, excepturi repudiandae magni optio odio doloribus? Facilisi lobortisal morbi fringilla urna amet sed ipsum.',
  },
];
export const currentPost = [
  {
    name: 'Cristiano Ronaldo',
    id: 1,
    market_price: 1000,
    specialization: 'futsal',
    player_record: 'Olympic Special',
    quantity: 1,
    desc: 'Neque aut veniam consectetur magnam libero, natus eius numquam reprehenderit hic at, excepturi repudiandae magni optio odio doloribus? Facilisi lobortisal morbi fringilla urna amet sed ipsum.',
  },
  {
    name: 'Lionel Messi',
    id: 2,
    market_price: 900,
    specialization: 'basketball',
    player_record: 'Record Special',
    quantity: 1,
    desc: 'Neque aut veniam consectetur magnam libero, natus eius numquam reprehenderit hic at, excepturi repudiandae magni optio odio doloribus? Facilisi lobortisal morbi fringilla urna amet sed ipsum.',
  },
  {
    name: 'Neymar Jr',
    id: 3,
    market_price: 800,
    specialization: 'futsal',
    player_record: 'Hall of Fame',
    quantity: 1,
    desc: 'Neque aut veniam consectetur magnam libero, natus eius numquam reprehenderit hic at, excepturi repudiandae magni optio odio doloribus? Facilisi lobortisal morbi fringilla urna amet sed ipsum.',
  },
  {
    name: 'Kylian Mbappe',
    id: 4,
    market_price: 1200,
    specialization: 'swimming',
    player_record: 'Olympic Special',
    quantity: 1,
    desc: 'Neque aut veniam consectetur magnam libero, natus eius numquam reprehenderit hic at, excepturi repudiandae magni optio odio doloribus? Facilisi lobortisal morbi fringilla urna amet sed ipsum.',
  },
];
export const cartList = [
  {
    name: 'Cristiano Ronaldo',
    id: 1,
    market_price: 1000,
    specialization: 'futsal',
    player_record: 'Olympic Special',
    quantity: 1,
    desc: 'Neque aut veniam consectetur magnam libero, natus eius numquam reprehenderit hic at, excepturi repudiandae magni optio odio doloribus? Facilisi lobortisal morbi fringilla urna amet sed ipsum.',
  },
  {
    name: 'Lionel Messi',
    id: 2,
    market_price: 900,
    specialization: 'basketball',
    player_record: 'Record Special',
    quantity: 1,
    desc: 'Neque aut veniam consectetur magnam libero, natus eius numquam reprehenderit hic at, excepturi repudiandae magni optio odio doloribus? Facilisi lobortisal morbi fringilla urna amet sed ipsum.',
  },

  {
    name: 'Kylian Mbappe',
    id: 4,
    market_price: 1200,
    specialization: 'swimming',
    player_record: 'Olympic Special',
    quantity: 1,
    desc: 'Neque aut veniam consectetur magnam libero, natus eius numquam reprehenderit hic at, excepturi repudiandae magni optio odio doloribus? Facilisi lobortisal morbi fringilla urna amet sed ipsum.',
  },
];
